### ISSUE TITLE
Signup stage_5b: Blockcerts setup OTP issuer JSON callback

### ISSUE THREAD

**Issue by alessandro-aglietti** [growingabit/pwa-backend#10]
Questo endpoint pubblico si aspetta di ricevere dall'app di blockcerts l'otp e deve rispondere con il json come

- https://hr.learningmachine.com/issuer/lm-issuer.json
- https://www.imsglobal.org/sites/default/files/Badges/OBv2p0/index.html#Issuer
- https://github.com/blockchain-certificates/blockchain-certificates.github.io/blob/master/samples/2.0/issuer-testnet.json

Ricevuto l'otp va a cercare per quale utente era stato generato questo codice da https://github.com/growingabit/pwa-backend/issues/9 e aggiorna lo stato dello stage

Il json issuer ha bisogno delle public key: https://github.com/orgs/growingabit/projects/1#card-4194983

**Comment by alessandro-aglietti** [comment]
Scoperto l'arcano, aspettatevi una POST con il seguente body
`{"bitcoinAddress":"1NNw6krqQV34x6tF1bCfJLDNmWNzueyMVp","nonce":"1234456"}`
ditemi l'url sul quale ve l'aspettate e configuro a modo il dominio che l'utente deve mettere nell'app Blockcerts che serve il json dell'issuer!

**Comment by alessandro-aglietti** [comment]
Se confermano la mia versione[1] allora possiamo preoccuparci dopo di generare gli address bitcoin di produzione tramite i quali pubblicheremo gli openbadges.

Il resto del flusso non cambia.

[1] http://community.blockcerts.org/t/learning-machine-contributes-android-app-to-blockcerts/227/3

**Comment by gianmarcobrescia** [comment]
@alessandro-aglietti 
è confermato il formato ?{"bitcoinAddress":"1NNw6krqQV34x6tF1bCfJLDNmWNzueyMVp","nonce":"1234456"}
il nonce sarebbe il nostro OTP?

**Comment by alessandro-aglietti** [comment]
esatto
