### ISSUE TITLE
Signup stage_0: Codice di invito

### ISSUE THREAD

**Issue by alessandro-aglietti** [growingabit/pwa-backend#2]
Riceve il codice di invito e ritorna il JSON completo dei meta dell'utente con gli stage di signup aggiornati

**Comment by canemacchina** [comment]
Il codice di invito sarebbe per la conferma della mail?
Non serve, la cosa la gestisce auth0. Basta abilitare il forcing della verifica delle email e siamo sicuri che nessuno può fare login senza aver verificato la mail

**Comment by alessandro-aglietti** [comment]
Il codice di invito non e' per la verifica della mail :D

Fatta la login con auth0 vogliamo comunque mandare avanti nel processo di registrazione solo chi ha ricevuto un codice di invito personale, grazie al quale possiamo associarlo ad altri metadati tipo la classe, l'anno scolastico etc.. .

Oltre che a limitare l'accesso solo alle persone che hanno ricevuto l'invito.

**Comment by alessandro-aglietti** [comment]
@gianmarcobrescia 
- crud entity codice di invito (Anno scolastico, Scuola, Classe, Specializzazione)
- all'inserimento di una entity viene generato un codice di invito
- duplica record copia i dati di sopra e genera un nuovo codice di invito

**Comment by canemacchina** [comment]
Il codice generato va associato ad un utente in fase di registrazione, altrimenti io quando l'utente fa la login e mi passa il codice, come capisco che ha messo il codice giusto?
Predispongo il campo nella entity, @gianmarcobrescia quando generi il codice riempilo.

Per fare i pignoli poi, per generare il codice di invito è meglio usare una stringa casuale criptograficamente sicura (usando SecureRandom)

**Comment by alessandro-aglietti** [comment]
Riguardo all'associazione utente codice di invito: pensavo che non vi era un associazione a priori fra utente e codice di invito.
L'associazione viene fatta quando un utente inserisce un codice di invito valido.
Il codice di invito non identifica l'utente ma la classe/scuola/anno scolastico/specializzazione alla quale lui appartiene.
In questo modo possiamo generare i codici di invito a monte e poi associarli dopo.

Visto che i codici di invito vengono lasciati di persona agli utenti durante delle sessioni apposite dove tutti effettueranno live la registrazione penso vada bene come approccio.

Riguardo al SecureRandom va benissimo ;)

**Comment by canemacchina** [comment]
Come vuoi. L'associazione a priori è un modo per verificare che il codice lo stia usando l'utente giusto.
Il tuo sistema è più come una product key di un software.
Comunque va bene. A maggior ragione allora dobbiamo usare codici criptograficamente sicuri ;)
