### ISSUE TITLE
Signup stage_5a: Blockcerts setup OTP

### ISSUE THREAD

**Issue by alessandro-aglietti** [growingabit/pwa-backend#9]
Va generato e salvato un OTP che ci ritornera' indietro quando l'utente aggiunge l'issuer sull'app di blockcerts.

**Comment by alessandro-aglietti** [comment]
L'otp deve essere mostrato dal frontend, poi ve lo ritroverete inviato indietro dall'app blockcerts assieme al bitcoin address dell'utente come descritto nella https://github.com/growingabit/pwa-backend/issues/10

**Comment by gianmarcobrescia** [comment]
Che formato deve avere l'OTP che generiamo?
